@startuml
top to bottom direction

rectangle "4NSWERS Q&A Forum" {

  actor Notifications
  actor User
  actor Guest
  actor Poster as PosterUser
  actor Responder as ResponderUser
  actor Commenter as CommentUser
  actor Voter as VoterUser
  actor "Community Admin" as AdminUser
 

  User <-- PosterUser
  User <-- ResponderUser
  User <-- CommentUser
  User <-- VoterUser
  User <-- AdminUser

}

@enduml

