# Official PHP image for Laravel projects
image: php:latest

# Use PostgreSQL as the service
services:
  - postgres:latest

# Set PostgreSQL environment variables
variables:
  POSTGRES_DB: project_name
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: secret

# Cache dependencies between builds
cache:
  paths:
    - vendor/
    - node_modules/

# Define the pipeline stages
stages:
  - test
  - deploy

# Install dependencies and prepare the application
before_script:
  # Update and install required packages
  - apt-get update -yqq
  - apt-get install -yqq git nodejs libpq-dev curl

  # Install PHP extensions for PostgreSQL
  - docker-php-ext-install pdo pdo_pgsql

  # Install Composer
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

  # Install Node dependencies if applicable
  - npm install

  # Setup environment for testing
  - cp .env.testing .env
  - php artisan key:generate
  - php artisan config:cache
  - php artisan migrate --env=testing

# Define the test stage
test:
  stage: test
  script:
    # Run backend tests
    - php vendor/bin/phpunit --coverage-text --colors=never
    # Run frontend tests, if any
    - npm test

# Define the deploy stage
deploy:
  stage: deploy
  script:
    - echo "Define your deployment script here!"
  environment: production
